askme/app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "AskMe"
urlpatterns = [
    path("", views.questions_list, name="question_list"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.register, name="register"),
    path("ask/", views.ask, name="ask"),
    path("question/<int:question_id>/", views.question_detail, name="question_detail"),
    path("settings/", views.settings, name="settings"),
    path("hot/", views.hot_questions, name="hot_questions"),
    path("<str:tag_name>/", views.questions_with_tag, name="get_by_tag"),
    path("question_like/<int:question_id>/", views.question_like, name="question_like"),
    path("answer_like/<int:answer_id>/", views.answer_like, name="answer_like"),
    path("set_useful/<int:answer_id>/", views.set_useful, name="set_useful"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

askme/askme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="AskMe")),
]

askme/app/templates/askme/components/best_members.html
<div class="mt-2 border-top border-dark border-2">
    <h2 class="mb-3">Best members</h2>
    <div class="d-flex flex-column gap-1 ">
        {% for member in best_members_arr %}
        <span>
            <a href="#" style="text-decoration: none;">{{member.user.username}}</a>            
        </span>
        {% endfor %}
    </div>
</div>

askme/app/templates/askme/components/pagination.html
{% if page_obj.paginator.count %}
<nav aria-label="Page navigation bootstrap">
    <ul class="pagination mt-3">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First page</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span
                    aria-hidden="true">&laquo;</span></a></li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><span aria-hidden="true">&raquo;</span></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last page</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

askme/app/templates/askme/components/question_card.html
{% load static %}
<div class="card question-card" data-question-id="{{question.id}}" data-is-liked="{% if question.is_liked %}True{% else %}False{% endif %}">
    <div class="card-body">
        <div class="row"> 
            <div class="col-3">
                <div class="mb-2">
                    <img src="{{question.author.profile.avatar.url}}" alt="{% static 'img/no_avatar' %}" class="img-fluid" style="object-fit: cover;">
                    <p class="text-center mt-2 fw-bold">{{ question.author.username }}</p>
                </div>
                <div class="d-flex align-items-center gap-2 justify-content-center">
                    <button class="like-button" style="width: 2rem; height: 2rem;"></button>
                    <span class="like-count">{{question.like_count}}</span>
                </div>
            </div>
            <div class="col">
                <div>
                    <h5 class="card-title">
                        
                        <a href="{{question.get_absolute_url}}" style="text-decoration: none;">
                        {{question.title}}
                        </a></h5>
                </div>
                <p class="card-text">
                  {{question.content}}</p>
                <div class="d-flex gap-5">
                    <a href="{% url 'AskMe:question_detail' question.id %}" class="card-link">Answers ({{question.answer_question.count}})</a>
                    <div>
                        Tags:
                        {% for tag in question.tags.all %}
                     
                        <a href="{% url 'AskMe:get_by_tag' tag %}" class="card-link">{{tag}}</a>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

askme/app/templates/askme/components/tags.html
    <div>
        <h1 class="mb-3">Popular tags</h1>
        <div class="d-flex gap-2 flex-wrap">
            {% for tag in most_popular_tags_arr %} 
            <a href="{% url 'AskMe:get_by_tag' tag.tag_ %}">
            <button  class="border border-dark p-2 rounded btn btn-{{tag.color}}">{{tag.tag_}}</button></a>
            {% endfor %}
        </div>
    </div>
    