askme/app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "AskMe"
urlpatterns = [
    path("", views.questions_list, name="question_list"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.register, name="register"),
    path("ask/", views.ask, name="ask"),
    path("question/<int:question_id>/", views.question_detail, name="question_detail"),
    path("settings/", views.settings, name="settings"),
    path("hot/", views.hot_questions, name="hot_questions"),
    path("<str:tag_name>/", views.questions_with_tag, name="get_by_tag"),
    path("question_like/<int:question_id>/", views.question_like, name="question_like"),
    path("answer_like/<int:answer_id>/", views.answer_like, name="answer_like"),
    path("set_useful/<int:answer_id>/", views.set_useful, name="set_useful"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

askme/askme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="AskMe")),
]

askme/app/templates/askme/base.html
{% load custom_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    {% csrf_token %}
    {% block style %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <nav class="navbar  navbar-expand-lg border-bottom border-2 border-dark bg-body-secondary">
    <div class="container-fluid">
        <div class="w-100 d-flex justify-content-between align-items-center">
            <a class="navbar-brand" href="{% url 'AskMe:question_list' %}">StackOverflow 2.0</a>

            <form class="d-flex col-7" method="get" enctype="multipart/form-data">
                {% csrf_token %}
                <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search" value="" name="question_title">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
              </form>
              {% if request.user.is_authenticated %}
              <a href="{% url 'AskMe:ask' %}">
                <button class="btn btn-outline-success" type="submit">Ask</button>
              </a>
              {% else %}

              <a href="{% url 'AskMe:login' %}?continue={% url 'AskMe:ask' %}">
                <button class="btn btn-outline-success" type="submit">Ask</button>
              </a>
              {% endif %}

            

            <div class="d-flex gap-3">
                {% if request.user.is_authenticated %}
                <a href="#"  style="text-decoration: none;"><img src="{{request.user.profile.avatar.url}}" class="img-thumbnail"  style="height: 50px; display: block; width: 50px; object-fit: cover; " alt="Photo"></a>
                <div >
                    
                    <div>
                        {{request.user.username}}
                    </div>
                    <div>
                        <a href="{% url 'AskMe:settings' %}">Settings</a>
                        <a href="{% url 'AskMe:logout' %}">Logout</a>
                    </div>
                    {% else %}
                    <div>
                        <a href="{% url 'AskMe:login' %}?continue={{ request.get_full_path }}" style="text-decoration: none;">Login</a>
                        <a href="{% url 'AskMe:register' %}" style="text-decoration: none;">Register</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </nav>
    <main class="container mt-3">
        <div class="row gap-2">
        <div class="col-9">
        {% block content %}
            {% endblock %}
        </div>
            <div class="col">
                {% most_popular_tags %}
                {% best_members %}
            </div>
        </div>
    </main>
</div>
</body>
</html>