askme/app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "AskMe"
urlpatterns = [
    path("", views.questions_list, name="question_list"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.register, name="register"),
    path("ask/", views.ask, name="ask"),
    path("question/<int:question_id>/", views.question_detail, name="question_detail"),
    path("settings/", views.settings, name="settings"),
    path("hot/", views.hot_questions, name="hot_questions"),
    path("<str:tag_name>/", views.questions_with_tag, name="get_by_tag"),
    path("question_like/<int:question_id>/", views.question_like, name="question_like"),
    path("answer_like/<int:answer_id>/", views.answer_like, name="answer_like"),
    path("set_useful/<int:answer_id>/", views.set_useful, name="set_useful"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

askme/askme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="AskMe")),
]

askme/app/templates/askme/questions/ask.html
{% extends "askme/base.html" %}

<body>



    <main class="container mt-3">
        {% block content %}



        <div class="row gap-4">
            <div class="d-flex flex-column">
                <h1 class="mb-3">New Question</h1>
                <form method="post">
                    {% csrf_token %}
                    
                    <div class="d-flex gap-2 align-items-baseline mb-3">
                        <label for="{{ form.title.id_for_label }}" class="col-2 col-form-label fs-4" style="font-weight: 500;">
                            Title
                        </label>
                        <div class="flex-grow-1">
                            {{ form.title }}
                            {% if form.title.errors %}
                                <div class="text-danger">{{ form.title.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="d-flex gap-2 align-items-baseline mb-3">
                        <label for="{{ form.content.id_for_label }}" class="col-2 col-form-label fs-4" style="font-weight: 500;">
                            Text
                        </label>
                        <div class="flex-grow-1">
                            {{ form.content }}
                            {% if form.content.errors %}
                                <div class="text-danger">{{ form.content.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    
  
                    <div class="d-flex gap-2 align-items-baseline mb-3">
                        <label for="{{ form.tags.id_for_label }}" class="col-2 col-form-label fs-4" style="font-weight: 500;">
                            Tags
                        </label>
                        <div class="flex-grow-1">
                            {{ form.tags }}
                            {% if form.tags.help_text %}
                                <small class="form-text text-muted">{{ form.tags.help_text }}</small>
                            {% endif %}
                            {% if form.tags.errors %}
                                <div class="text-danger">{{ form.tags.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    
                    <button type="submit" class="btn btn-outline-success">
                        Publish
                    </button>
                </form>
            </div>
        </div>
            {% endblock %}

askme/app/templates/askme/questions/hot.html
{% extends "askme/base.html" %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/like_button.css' %}">
<script src="{% static 'js/like_button.js' %}" defer></script>
{% endblock %}

        {% block content %}
        <div class="d-flex justify-content-start gap-3 align-items-center w-100">
            <h1>
                Hot Questions
            </h1>
            <a href="{% url 'AskMe:question_list' %}">
                New Questions!
            </a>
        </div>


        <div class="row gap-4">
         
                <div class="d-flex flex-column gap-2">
                    {% for question in questions %}
                    {% include 'askme/components/question_card.html' with questions=questions %}

                    
                    {% endfor %}

                </div>
                {% include 'askme/components/pagination.html' with page_obj=questions %}

                    </div>
                    {% endblock %}

askme/app/templates/askme/questions/index.html
{% extends "askme/base.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/like_button.css' %}">
<script src="{% static 'js/like_button.js' %}" defer></script>
{% endblock %}


        {% block content %}
        <div class="d-flex justify-content-start gap-3 align-items-center w-100">
            <h1>
                New Questions
            </h1>
            <a href="{% url 'AskMe:hot_questions' %}">
                Hot Questions!
            </a>
        </div>


        <div class="row gap-4">
            
                <div class="d-flex flex-column gap-2">
                    {% for question in questions %}
                    {% include 'askme/components/question_card.html' with questions=questions %}
                    {% empty %}
                    <div class="d-flex align-items-center gap-2">
                        <h3>Sorry, there is no such question!</h3>
                        <a href="{% url 'AskMe:ask' %}">Create one?</a>
                    </div>

                    
                    {% endfor %}

                </div>
                {% include 'askme/components/pagination.html' with page_obj=questions %}

                    </div>
                    {% endblock %}

askme/app/templates/askme/questions/question.html
{% extends "askme/base.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/like_button.css' %}">
<script src="{% static 'js/like_button.js' %}" defer></script>
{% endblock %}


<body>
    <main class="container mt-3">
        {% block content %}
  

        <div class="row gap-4">
                <div class="d-flex flex-column gap-3">
                    <div class="card border-0 border-bottom border-dark border-2 rounded-0 question-card" data-question-id="{{question.id}}" 
                    data-is-liked="{% if question.is_liked %}True{% else %}False{% endif %}"
                    data-is-author="{% if request.user == question.author %}True{% else %}False{% endif %}">
                        <div class="card-body">
                            <div class="row"> 
                                <div class="col-3">
                                    <div class="mb-2">
                                        <img src="{{question.author.profile.avatar.url}}" alt="{% static 'img\no_avatar.jpg' %}" class="img-fluid" style="object-fit: cover;">
                                        <p class="text-center mt-2 fw-bold">{{ question.author.username }}</p>
                                    </div>
                                    <div class="d-flex align-items-center gap-2 justify-content-center">
                                        <button class="like-button" style="width: 2rem; height: 2rem;"></button>
                                        <span class="like-count">{{question.like_count}}</span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div>
                                        <h5 class="card-title">{{question.title}}</h5>
                                    </div>
                                    <p class="card-text">
                                        {{question.content}}
                                    </p>
                                    <div class="d-flex gap-5">
                                        <div>
                                            Tags:
                                            {% for tag in question.tags.all %}
                                            <a href="{% url 'AskMe:get_by_tag' tag %}" class="card-link">{{tag}}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="border-dark border-2 d-flex flex-column border-bottom gap-2">
                        {% for answer in answers %}
                        <div class="card mb-1 answer-card {{ answer.useful_class }}" 
                            data-answer-id="{{answer.id}}" 
                            data-is-liked="{% if answer.is_liked %}True{% else %}False{% endif %}" 
                            data-is-helpful="{% if answer.helpful %}True{% else %}False{% endif %}">
                            <div class="card-body">
                                <div class="row"> 
                                    <div class="col-3">
                                        <div class="mb-2">
                                            <img src="{{answer.author.profile.avatar.url}}" alt="{% static 'img\no_avatar.jpg' %}" class="img-fluid" style="object-fit: cover;">
                                            <p class="text-center mt-2 fw-bold">{{ answer.author.username }}</p>
                                        </div>
                                        <div class="d-flex align-items-center gap-2 justify-content-center">
                                            <button class="answer-like-button" style="width: 2rem; height: 2rem;"></button>
                                            <span class="answer-like-count">{{answer.like_count}}</span>
                                        </div>
                                    </div>
                                    <div class="col d-flex flex-column justify-content-between">
                                        <p class="card-text">
                                            {{answer.content}}
                                        </p>
                                        <div class="d-flex align-items-center form-check gap-3 mb-2">
                                            <input class="form-check-input helpful-checkbox" type="checkbox" 
                                                   value="{{ answer.id }}" 
                                                   id="flexCheckDefault_{{ answer.id }}" 
                                                   {% if answer.helpful %}checked{% endif %} 
                                                   style="height: 20px; width: 20px;">
                                            <label class="form-check-label" for="flexCheckDefault_{{ answer.id }}">
                                                Useful answer 
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% include 'askme/components/pagination.html' with page_obj=answers %}
                    </div>
                    <form method="post">
                    {% csrf_token %}
                    <div class="d-flex flex-column gap-2">
                        <div class="d-flex gap-2 align-items-baseline mb-3">
                            <h4>{{form.content.label}}</h4>
                            {{form.content}}
                        </div>
                        <button type="submit" class="btn btn-outline-success" style="height: fit-content; width: fit-content;">Publish</button>
                    </div>
                </form>
                </div>
            </div>
            {% endblock %}

askme/app/templates/askme/questions/tag.html
{% extends "askme/base.html" %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/like_button.css' %}">
<script src="{% static 'js/like_button.js' %}" defer></script>
{% endblock %}

        {% block content %}
        <div class="d-flex justify-content-start gap-3 align-items-center w-100">
            <h1>
                Tag : {{tag}}
            </h1>

        </div>


        <div class="row gap-4">

                <div class="d-flex flex-column gap-2">
                    {% for question in questions %}
                    {% include 'askme/components/question_card.html' with questions=questions %}

                    
                    {% endfor %}

                </div>
                {% include 'askme/components/pagination.html' with page_obj=questions %}

                    </div>
                    {% endblock %}